### ISSUE TITLE
Flaky #init was called twice in a row. Make sure to call #release after every #init

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.libraries#46]
```
java.lang.IllegalStateException: #init was called twice in a row. Make sure to call #release after every #init
at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
at androidx.test.espresso.intent.Intents.internalInit(Intents.java:308)
at androidx.test.espresso.intent.Intents.init(Intents.java:126)
at net.twisterrob.android.test.junit.SensibleActivityTestRule.afterActivityLaunched(SensibleActivityTestRule.java:94)
at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:384)
at net.twisterrob.android.test.junit.SensibleActivityTestRule.launchActivity(SensibleActivityTestRule.java:75)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:541)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```
Local run
[connected.zip](https://github.com/TWiStErRob/net.twisterrob.libraries/files/11016860/connected.zip)

**Comment by TWiStErRob** [comment]
Consistent repro:
https://github.com/TWiStErRob/net.twisterrob.libraries/pull/40 "Fix \#41" commit 6120686
Run `DetailedFailureHandlerTest` test locally on API 21.

**Comment by TWiStErRob** [comment]
`finishActivity` in my rule wasn't called, because it was already finished by the test code.
