### ISSUE TITLE
Take screenshot before killing external app

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.libraries#58]
https://github.com/TWiStErRob/net.twisterrob.inventory/pull/277/checks?check_run_id=14355079522

![image](https://github.com/TWiStErRob/net.twisterrob.libraries/assets/2906988/bf042ce3-002c-472a-b87e-6ce41d3105fa)

```
java.lang.AssertionError: com.android.documentsui was still open at the end of the test, pressing Back 1 times and Home 0 times helped kill it.
at org.junit.Assert.fail(Assert.java:89)
at net.twisterrob.inventory.android.test.ExternalAppKiller.after(ExternalAppKiller.java:55)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
at net.twisterrob.android.test.junit.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:82)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```

**Comment by TWiStErRob** [comment]
Hmm, actually this was attached: 
![image](https://github.com/TWiStErRob/net.twisterrob.libraries/assets/2906988/b446d196-5874-404b-bce3-7b089324af63)
which means real failure is hidden!
